config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :blog_posts

  #get "/blog_posts/new", to: "blog_posts#new", as: :new_blog_post
  #get "/blog_posts/:id/edit", to: "blog_posts#edit", as: :edit_blog_post
  #patch "/blog_posts/:id", to: "blog_posts#update"
  #delete "/blog_posts/:id", to: "blog_posts#destroy"
  #get "/blog_posts/:id", to: "blog_posts#show", as: :blog_post
  #post "/blog_posts", to: "blog_posts#create", as: :blog_posts
  
  
  root "blog_posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/blog_post.rb
class BlogPost < ApplicationRecord

    has_rich_text :content

    validates :title, presence: true
    validates :content, presence: true

    scope :sorted, ->{order(arel_table[:published_at].desc.nulls_last).order(updated_at: :desc) }
    scope :draft, -> {where(published_at: nil)}
    scope :published, -> {where("published_at <= ?", Time.current)}
    scope :scheduled, -> {where("published_at > ?", Time.current)}

    def draft?
        published_at.nil?
    end

    def published?
        published_at? && published_at <= Time.current
    end

    def scheduled?
        published_at? && published_at > Time.current
    end


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blog_posts_controller.rb
class BlogPostsController < ApplicationController
    before_action :authenticate_user!, except: [:index, :show]
    before_action :set_blog_post, except: [:index, :new, :create] #only: [:show, :edit, :update, :destroy]
    

    def index
        if user_signed_in?
        @blog_posts = BlogPost.sorted
        else
        @blog_posts = BlogPost.published.sorted
        end
    end

    def show
    end

    def new
        @blog_post = BlogPost.new
    end

    def create
        @blog_post = BlogPost.new(blog_post_params)
        if @blog_post.save
            redirect_to @blog_post
        else
            render :new, status: :unprocessable_entity
        end
    end

    def edit
    end 

    def update
        if @blog_post.update(blog_post_params)
            redirect_to @blog_post
        else
            render :edit, status: :unprocessable_entity
        end 
    end 

    def destroy
        @blog_post.destroy
        redirect_to root_path
    end 

    private

    def blog_post_params
        params.require(:blog_post).permit(:title, :content, :published_at)
    end

    def set_blog_post
        if user_signed_in?
            @blog_post = BlogPost.find(params[:id])
        else
            @blog_post = BlogPost.published.find(params[:id])
        end
    rescue ActiveRecord::RecordNotFound
        redirect_to root_path
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/blog_posts/_form.html.erb
<%= form_with(model: @blog_post, multipart: true) do |form|%>
<%= hidden_field_tag :authenticity_token, form_authenticity_token %>
    <% if form.object.errors.any?%>
        <div>
            <% form.object.errors.full_messages.each do |message|%>
            <div> <%= message %> </div>
            <%end%>
        </div>
    <%end%>

    <div class ="field form-group">
    <%#= form.label :title, style: "display: block"%>
    <%= label_tag "title", "Blog Title" %>
    <%= form.text_field :title, class:"form-control"%>
    </div>

    <div class ="field form-group">
    <%#= form.label :body, style: "display: block"%>
    <%= label_tag "content", "Blog Content" %>
    <%= form.rich_text_area :content, class:"form-control"%>
    </div>

    <div class ="field form-group">
        <%= form.label :published_at%>
        <%= form.datetime_select :published_at, include_blank: true %>
        <%= button_tag "Set to current Date and Time", type: "button", onclick: "insertCurrentDateTime()", class:"btn btn-link ml-3" %>

    </div>

    <%= form.submit class:"btn btn-dark"%>

<% end %>

app/views/blog_posts/_header.html.erb
   <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    
  <div class="container-fluid">
    <%= link_to "My Blog", root_path, class:"navbar-brand"%>

        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
      
      <% if user_signed_in?%>
        <li class="nav-link">
        <%= link_to "Profile", edit_user_registration_path, class:"btn nav-link" %>
        </li>

        <li class="nav-link">
        <%= button_to "Log Out", destroy_user_session_path, method: :delete, class: "btn nav-link"%>
        </li>

        

      <%else%>
        <li class="nav-link">
        <%= link_to "Log In", new_user_session_path, class:"nav-link" %>
        </li>

        <li class="nav-link">
        <%= link_to "Sign Up",  new_user_registration_path, class:"nav-link" %>
        </li>
    <%end%>

     
     
    
    </ul>
    </div>
    </ul>
  </div>
</nav>

app/views/blog_posts/edit.html.erb
<h1> Edit Blog Post</h1>
<br>

<%= render partial: "form", locals: {blog_post: @blog_post} %>
<br>
<%= button_to "Delete Post", blog_post_path, method: :delete, class: "delete-button", onclick: "return confirm('Are you sure?');", class:"btn btn-danger" %>
<br>
<%= button_to "Back", root_path, method: :get, class:"btn btn-primary"%>

app/views/blog_posts/index.html.erb
<div class="container">
  <div class="d-flex justify-content-between align-items-center">
  <h1 class="mb-0">My Blog</h1>
   <%= button_to "New Blog Post", new_blog_post_path, method: :get, class: "btn btn-primary" %>
   </div>
   <br>


  <% @blog_posts.each do |blog_post| %>
    

    <div class="card mb-3">
      <div class="card-body">
        <% if blog_post.draft?%>
      <div class="alert alert-secondary">Draft</div>

      <%elsif blog_post.scheduled?%>
      <div class="alert alert-primary">Blog is scheduled for: <%= blog_post.published_at.strftime('%B %d, %Y %H:%M') %></div>

      <% end%>

        <h4 class="card-title"><%= link_to blog_post.title, blog_post %></h4>
        <p class="card-text"><%= blog_post.content%></p>
      </div>
    </div>
  <% end %>
</div>

app/views/blog_posts/new.html.erb
<h1> Create New Blog Post</h1>

<%= render partial: "form", locals: {blog_post: @blog_post} %>

<br>

<%= button_to "Back", root_path, method: :get, class:"btn btn-primary"%>

app/views/blog_posts/show.html.erb
<div class="jumbotron">
  <h1 class="display-4"><%= @blog_post.title%></h1>
  <hr class="my-4">
  <%= @blog_post.content%>
  <br><br/>

  <div>
    <% if user_signed_in?%>
        <%= button_to "Edit Blog Post", edit_blog_post_path, method: :get, class:"btn btn-dark" %> 
        <%#= button_to "Delete", blog_post_path, method: :delete, class: "delete-button", onclick: "return confirm('Are you sure?');", class:"btn btn-danger" %>
    <%end%>
    </div>
</div>

<div class="row">

    <div class="col-md-3">
    <%= button_to "Back", root_path, method: :get, class:"btn btn-primary"%>
    </div>
</div>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dan's Blog</title>
    <%= render "blog_posts/header" %>
    
   
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1, shrink-to-fit=no">
     <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "actiontext": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag 'datetime_functions' %>
    <%= javascript_importmap_tags %>
    

    <%#= javascript_pack_tag 'trix' %>

  </head>

  <body>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    

  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
 

  <div class="container">
    <%= yield %>
 </div>
  </body>
</html>